### ISSUE TITLE
Template URL for RDGWStack Doesn't Exist

### ISSUE THREAD

**Issue by whono** [aws-ia/cfn-ps-freeradius-mfa-workspaces#10]
When testing solution scenario 2 "Deploy FreeRADIUS MFA with Amazon WorkSpaces into a new AWS Managed Microsoft AD and VPC" with RD Gateway option turned on, received error on RDGWStack:
```
S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html
```
We saw the template URL for RDGWStack was pointing to:
```
https://aws-ia-us-east-1.s3.us-east-1.amazonaws.com/cfn-ps-freeradius-mfa-workspaces/submodules/cfn-ps-microsoft-rdgateway/templates/rdgw-domain.template.yaml
```
However, after checking internally, I realized this path/object doesn't exist. I wonder if you can confirm the template URL for the RDGWStack.

**Comment by vsnyc** [comment]
Thanks for the report. This option requires RDGW to be added as a submodule, but it wasn't the case. I'll create a PR with a fix.
